### ISSUE TITLE
Runic Enchanting Table Doesn't Function

### ISSUE THREAD

**Issue by badooga** [brotazoa/runic_enchanting#3]
The runic enchanting table doesn't appear to provide any functionality, even when used like the image in the mod description. If there are any other criteria needed to use it, the mod does not communicate it.

![image](https://github.com/brotazoa/runic_enchanting/assets/33851191/2d0cf9b1-514b-45b9-aaa6-90ec77a4788d)

Tested on Fabric 1.20.1 and Quilt with only Fabric/Quilt API and Runic Enchanting installed.

**Comment by brotazoa** [comment]
That is not a valid recipe. The rune pages have to be in the correct order. You can use a recipe viewer like REI or EMI to view all the rune enchanting recipes.

**Comment by badooga** [comment]
Nothing in-game or in the mod description properly indicates that the runes require a specific order - the description just says "a sequence" - and nothing that I could find in-game tells you what those recipes are when you aren't using REI. At minimum, this REI/EMI requirement should be communicated in the mod description so that others don't make the same conclusion.
